### ISSUE TITLE
Crash on Arch Linux when trying to open file

### ISSUE THREAD

**Issue by piotr-szegda** [flathub/org.videolan.VLC#40]
Version from standard system repository work without problem.
 
```VLC media player 3.0.3 Vetinari (revision 3.0.3-1-0-gc2bb759264)
[00000000022901a0] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
org.kde.knotifications: env says KDE is running but SNI unavailable -- check KDE_FULL_SESSION and XDG_CURRENT_DESKTOP
[000000000231d750] main playlist: playlist is empty
QXcbConnection: XCB error: 3 (BadWindow), sequence: 948, resource id: 20971884, major code: 40 (TranslateCoords), minor code: 0
[00007f58a4c05a20] avi demux error: no key frame set for track 1
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva error: /usr/lib/dri/radeonsi_drv_video.so init failed
libva info: va_openDriver() returns 2
[00007f588c0028f0] glconv_vaapi_x11 gl error: vaInitialize: resource allocation failed
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns -1
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
[00007f588c0028f0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns -1
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
[00007f588c0028f0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error
```

**Comment by marcosps** [comment]
@piotr-szegda this was fixed in my last flatpak update. Can you please check again?

**Comment by piotr-szegda** [comment]
Unfortunately still crash. 
pszegda@archlinux ~]$ flatpak update
Looking for updates...
[pszegda@archlinux ~]$ flatpak run org.videolan.VLC 
VLC media player 3.0.3 Vetinari (revision 3.0.3-1-0-gc2bb759264)
[0000000000ef41a0] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
org.kde.knotifications: env says KDE is running but SNI unavailable -- check KDE_FULL_SESSION and XDG_CURRENT_DESKTOP
[0000000000f81750] main playlist: playlist is empty
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva error: /usr/lib/dri/radeonsi_drv_video.so init failed
libva info: va_openDriver() returns 2
[00007f3ea80028f0] glconv_vaapi_x11 gl error: vaInitialize: resource allocation failed
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns -1
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
[00007f3ea80028f0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns -1
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
[00007f3ea80028f0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error

**Comment by Alexander-Wilms** [comment]
I think I encounter the same crash with this media file: https://github.com/SuperTux/media/blob/master/video/SuperTuxDemo.wmv

```
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns -1
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
[00007fffac004630] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
[00007fffb4c59810] avcodec decoder: Using Intel i965 driver for Intel(R) Ivybridge Mobile - 1.8.3 for hardware decoding
[New LWP 24]

Thread 17 "vlc" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 24]
gen7_mfd_vc1_decode_init (gen7_mfd_context=0x7fffb4d128f0, decode_state=0x7fffac605288, 
    ctx=0x7fffac602480) at gen7_mfd.c:1360
1360    gen7_mfd.c: No such file or directory.
(gdb) bt full
#0  0x00007fff9e6fd71b in gen7_mfd_decode_picture (gen7_mfd_context=
    0x7fffb4d128f0, decode_state=0x7fffac605288, ctx=0x7fffac602480) at gen7_mfd.c:1360
        bitplane_width = <optimized out>
        src_h = <optimized out>
        dst = <optimized out>
        width_in_mbs = 40
        height_in_mbs = <optimized out>
        src_w = <optimized out>
        src = <optimized out>
        obj_surface = <optimized out>
        intensity_compensation = <optimized out>
        pic_param = 0x7fffb0080c20
        bo = <optimized out>
        width_in_mbs = <optimized out>
        picture_type = 0
        next_slice_param = <optimized out>
        next_slice_group_param = <optimized out>
        slice_data_bo = <optimized out>
        i = <optimized out>
        batch = 0x7fffb4c8a350
        pic_param = 0x7fffb0080c20
        slice_param = <optimized out>
        j = <optimized out>
        gen7_mfd_context = 0x7fffb4d128f0
        decode_state = 0x7fffac605288
        vaStatus = <optimized out>
        __PRETTY_FUNCTION__ = "gen7_mfd_decode_picture"
---Type <return> to continue, or q <return> to quit---
#1  0x00007fff9e6fd71b in gen7_mfd_decode_picture (gen7_mfd_context=
    0x7fffb4d128f0, decode_state=0x7fffac605288, ctx=0x7fffac602480) at gen7_mfd.c:1826
        next_slice_param = <optimized out>
        next_slice_group_param = <optimized out>
        slice_data_bo = <optimized out>
        i = <optimized out>
        batch = 0x7fffb4c8a350
        pic_param = 0x7fffb0080c20
        slice_param = <optimized out>
        j = <optimized out>
        gen7_mfd_context = 0x7fffb4d128f0
        decode_state = 0x7fffac605288
        vaStatus = <optimized out>
        __PRETTY_FUNCTION__ = "gen7_mfd_decode_picture"
#2  0x00007fff9e6fd71b in gen7_mfd_decode_picture (ctx=0x7fffac602480, profile=<optimized out>, codec_state=0x7fffac605288, hw_context=0x7fffb4d128f0) at gen7_mfd.c:2679
        gen7_mfd_context = 0x7fffb4d128f0
        decode_state = 0x7fffac605288
        vaStatus = <optimized out>
        __PRETTY_FUNCTION__ = "gen7_mfd_decode_picture"
#3  0x00007fffa8a74faf in vaEndPicture () at /lib/libva.so.1
#4  0x00007fffaa725b4a in  () at /app/lib/libavcodec.so.58
#5  0x00007fffaa73365c in  () at /app/lib/libavcodec.so.58
#6  0x00007fffaa75b388 in  () at /app/lib/libavcodec.so.58
#7  0x00007fffaa2a159b in  () at /app/lib/libavcodec.so.58
#8  0x00007fffaa2a4558 in avcodec_send_packet () at /app/lib/libavcodec.so.58
#9  0x00007fffab753647 in DecodeVideo (error=<synthetic pointer>, pp_block=<optimized out>, p_de---Type <return> to continue, or q <return> to quit---
c=<optimized out>) at codec/avcodec/video.c:1022
        pkt = 
          {buf = 0x0, pts = -9223372036854775808, dts = 1, data = 0x7fffb4d236a0 "", size = 39751, stream_index = 0, flags = 0, side_data = 0x0, side_data_elems = 0, duration = 0, pos = -1, convergence_duration = 0}
        ret = <optimized out>
        frame = 0x0
        i_pts = <optimized out>
        p_pic = <optimized out>
        i_used = <optimized out>
        not_received_frame = <optimized out>
        eos_spotted = <optimized out>
        p_sys = <optimized out>
        p_context = <optimized out>
        b_need_output_picture = <optimized out>
        p_block = <optimized out>
        current_time = <optimized out>
        pp_block = <optimized out>
        error = false
#10 0x00007fffab753647 in DecodeVideo (p_dec=<optimized out>, p_block=<optimized out>)
    at codec/avcodec/video.c:1234
        pp_block = <optimized out>
        error = false
#11 0x00007ffff7b0ff9b in DecoderDecode (p_dec=0x7fffb4c59810, p_block=0x7fffb4d23630)
    at input/decoder.c:1332
        p_owner = 0x7fffb4c5a770
        ret = <optimized out>
---Type <return> to continue, or q <return> to quit---
#12 0x00007ffff7b0fb74 in DecoderProcess (p_dec=p_dec@entry=0x7fffb4c59810, p_block=p_block@entry=0x7fffb4d23630) at input/decoder.c:1455
        p_owner = 0x7fffb4c5a770
        reload = <optimized out>
        __func__ = "DecoderProcess"
        packetize = <optimized out>
#13 0x00007ffff7b1021b in DecoderThread (p_data=<optimized out>) at input/decoder.c:1611
        p_block = 0x7fffb4d23630
        canc = 0
        __cancel_buf = 
            {__cancel_jmp_buf = {{__cancel_jmp_buf = {140736226240368, -5196287233637237365, 140736454821646, 140736454821647, 140736455878400, 140736822596720, 5196187095341186443, 5196304222672895371}, __mask_was_saved = 0}}, __pad = {0x7fffc2759f30, 0x0, 0x6c7108, 0x0}}
        __cancel_routine = 0x7ffff7b0e170 <vlc_fifo_Cleanup>
        __cancel_arg = <optimized out>
        __not_first_call = <optimized out>
        p_dec = <optimized out>
        p_owner = <optimized out>
        paused = false
        __func__ = "DecoderThread"
#14 0x0000003131007444 in  () at /lib/libpthread.so.0
#15 0x00000031308e827f in clone () at /lib/libc.so.6
```

**Comment by mikelpr** [comment]
same on fedora 28, the rpmfusion packages work but the flatpak doesn't

**Comment by glaubersm** [comment]
vlc 3.0.3 is still crashing on Arch Linux when I try to play a WMV file

> VLC media player 3.0.3 Vetinari (revision 3.0.3-1-0-gc2bb759264)
[000000000192cf00] main libvlc: Executando o VLC com a interface padrão. Use 'cvlc' para usar o VLC sem interface.
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
[00007f198cc6ca10] avcodec decoder: Using Intel i965 driver for Intel(R) Ivybridge Mobile - 1.8.3 for hardware decoding

**Comment by glaubersm** [comment]
vlc 3.0.4 also crashes on Arch Linux when I play wmv file.

**Comment by MatMaul** [comment]
Ok I can reproduce, looks like the crash happens in the vaapi lib. Unfortunately to update it to a more recent version we need to switch the new freedesktop runtime, which will probably come with Qt 5.12 Sdk.

**Comment by MatMaul** [comment]
This should be fixed in the upcoming version (should be up in less than 1h) which has been rebased using Qt5.12/18.08. SuperTuxDemo.wmv works fine for me with this version.
